### PR TITLE
upgraded to use block memory

### PR DESCRIPTION
**Pull request by zack-vii**
was actually pretty easy now, I think the switch from BRAM to DMA could be easily implemented, at least the current implementation could support it.

### CODE REVIEW

**Comment by zack-vii** [comment]
don't merge yet found a bug

**Comment by AndreaRigoni** [comment]
That's great ! I'll wait until the bug is fixed ..

**Comment by zack-vii** [comment]
writing to the memblock works now the program might not be able to read from it in time atm. my first tests failed. a small test script is in rptest.tdi

**Comment by AndreaRigoni** [comment]
Thanks Timo ! I'll put it on a branch

**Comment by zack-vii** [comment]
This would be the final version - using BRAM

**Pull request closed without merging**
